language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t biflex/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true biflex/docker-react npm run test

